
[platformio]
boards_dir   = RAK_PATCH_V2/rakwireless/boards
default_envs = t114
;default_envs = rak4631

; ── Settings communs ─────────────────────────────────────────────────────────
[env]
platform      = nordicnrf52
framework     = arduino
monitor_speed = 115200
lib_deps      = beegee-tokyo/SX126x-Arduino@^2.0.32

; ── Heltec T114 ──────────────────────────────────────────────────────────────
[env:t114]
board = heltec_t114

build_src_filter =
    ${env.build_src_filter}
    +<../RAK_PATCH_V2/rakwireless/variants/heltec_t114>

build_flags =
    -I RAK_PATCH_V2/rakwireless/variants/heltec_t114
    -D NRF52_SERIES
    -D USE_LFXO
    -D BOARD_T114

; [env:t114]
; board = heltec_t114

; build_src_filter =
;     ${env.build_src_filter}
;     +<../RAK_PATCH_V2/rakwireless/variants/heltec_t114>

; build_flags =
;     -I RAK_PATCH_V2/rakwireless/variants/heltec_t114
;     -D USE_LFXO
;     -D BOARD_RAK4631

; ── RAK4631 (WisBlock RAK4630 core) ──────────────────────────────────────────
[env:rak4631]
board = rak4630

build_src_filter =
    ${env.build_src_filter}
    +<../RAK_PATCH_V2/rakwireless/variants/rak4630>

build_flags =
    -I RAK_PATCH_V2/rakwireless/variants/rak4630
    -D BOARD_RAK4631

