My Project: LoRaSlave Class Reference
LoRaSlave Class Reference
Slave-side LoRa P2P protocol controller.
#include <lora_slave.h>
Public Member Functions
LoRaSlave ()
Constructs a slave controller with default runtime state.
void begin ()
Initializes LED, watering, and radio resources.
void loop ()
Runs one slave protocol cycle.
Static Public Attributes
static constexpr uint8_t NODE_ID = 3
Static node identifier used in LoRa frames.
Private Types
enum FrameType : uint8_t { FRAME_HELLO = 0x10 , FRAME_ACK_HELLO = 0x11 , FRAME_CMD = 0x20 , FRAME_ACK_CMD = 0x21 }
Frame types exchanged with the LoRa master.
enum CommandType : uint8_t {
CMD_NONE = 0x00 , CMD_PING = 0x01 , CMD_LED_ON = 0x02 , CMD_LED_OFF = 0x03 ,
CMD_TEXT_MESSAGE = 0x10 , CMD_BATTERY = 0x11 , CMD_REBOOT = 0x12 , CMD_STATUS = 0x13 ,
CMD_SET_PERIOD = 0x14 , CMD_VALVE_OPEN = 0x20 , CMD_VALVE_CLOSE = 0x21 , CMD_WATER_TIME = 0x22 ,
CMD_WATER_ABORT = 0x23 , CMD_WATER_STATUS = 0x24 , CMD_OTA_MODE = 0x30
}
Command codes supported by the slave protocol.
enum AckStatus : uint8_t { ACK_STATUS_OK = 0x00 , ACK_STATUS_ERROR = 0x01 }
Status values encoded in command acknowledgments.
Private Member Functions
void ledInit ()
Initializes the board LED GPIO.
void ledSet (bool on)
Sets the board LED state.
void resetFlags ()
Clears radio event flags and receive size.
uint8_t nextSeq ()
Returns and advances the protocol sequence number.
uint8_t getStatusFlag () const
Builds the current node status flag byte.
uint16_t readBatteryMilliVolts () const
Reads the battery voltage.
uint32_t getUptimeSec () const
Returns node uptime.
uint16_t crc16Ccitt (const uint8_t *data, uint16_t len) const
Computes CRC-16/CCITT over a byte buffer.
uint8_t getFrameTotalLength (uint8_t payloadLen) const
Returns total frame length for a payload length.
uint8_t buildFrame (uint8_t type, uint8_t nodeId, uint8_t seq, const uint8_t *payload, uint8_t payloadLen)
Builds a protocol frame in txBuffer.
bool validateFrame (uint8_t expectedType, uint8_t expectedNode, uint8_t expectedSeq) const
Validates the last received frame against expected header values.
void printFrameDebug (const char *prefix, const uint8_t *buf, uint8_t len) const
Prints a frame for diagnostics.
bool initRadio ()
Initializes the LoRa radio.
bool sendFrameAndWaitTx (uint8_t totalLen)
Sends txBuffer and waits for TX completion.
bool waitForFrame (uint32_t timeoutMs)
Waits for one received frame.
bool sendHelloAndWaitAckOnce ()
Sends one HELLO frame and waits once for ACK.
bool sendHelloAndWaitAck ()
Sends HELLO frames with retries until ACK or retry exhaustion.
bool processOptionalCommand ()
Waits for and processes one optional command from the master.
bool sendAckCmd (uint8_t seq, uint8_t cmdCode, uint8_t ackStatus, const uint8_t *extraPayload, uint8_t extraLen)
Sends a command acknowledgment frame.
void nodeSleep (uint32_t sleepMs)
Waits between protocol cycles.
void checkWateringSafety ()
Runs watering safety supervision.
void enterBleOtaMode ()
Requests BLE OTA mode entry.
uint8_t getHelloFlags () const
Builds HELLO flag bits.
Static Private Member Functions
static void OnTxDone (void)
Static radio TX done callback bridge.
static void OnTxTimeout (void)
Static radio TX timeout callback bridge.
static void OnRxDone (uint8_t *payload, uint16_t size, int16_t rssi, int8_t snr)
Static radio RX done callback bridge.
static void OnRxTimeout (void)
Static radio RX timeout callback bridge.
static void OnRxError (void)
Static radio RX error callback bridge.
static void OnCadDone (bool cadResult)
Static radio CAD done callback bridge.
Private Attributes
uint8_t txBuffer [MAX_BUFFER_SIZE]
Transmit frame buffer.
uint8_t rxBuffer [MAX_BUFFER_SIZE]
Receive frame buffer.
volatile bool txDoneFlag
Set when radio TX completes.
volatile bool txTimeoutFlag
Set when radio TX times out.
volatile bool rxDoneFlag
Set when radio RX completes.
volatile bool rxTimeoutFlag
Set when radio RX times out.
volatile bool rxErrorFlag
Set when radio RX reports an error.
volatile uint16_t rxSize
Size of the last received frame.
volatile int16_t lastRssi
RSSI of the last received frame.
volatile int8_t lastSnr
SNR of the last received frame.
uint8_t seqNum
Protocol sequence counter.
bool ledState
Cached LED state.
uint32_t sleepTimeMs
Current delay between protocol cycles.
uint32_t _lastAckHelloMs
millis() timestamp of the last acknowledged HELLO.
uint8_t _lastCmdSeq
Last command sequence processed.
Watering watering
Watering actuator and flow controller.
bool _justBooted
true until the first HELLO/status report has been sent.
Static Private Attributes
static constexpr uint32_t RF_FREQUENCY = 865000000UL
LoRa RF frequency, in hertz.
static constexpr int8_t TX_OUTPUT_POWER = 14
LoRa transmit power, in dBm.
static constexpr uint8_t LORA_BANDWIDTH = 0
SX126x bandwidth code.
static constexpr uint8_t LORA_SPREADING_FACTOR = 7
LoRa spreading factor.
static constexpr uint8_t LORA_CODINGRATE = 1
SX126x coding rate code.
static constexpr uint16_t LORA_PREAMBLE_LENGTH = 8
LoRa preamble length, in symbols.
static constexpr uint16_t LORA_SYMBOL_TIMEOUT = 0
LoRa symbol timeout for RX configuration.
static constexpr bool LORA_FIX_LENGTH_PAYLOAD = false
false to use variable-length packets.
static constexpr bool LORA_IQ_INVERSION = false
false to keep standard IQ polarity.
static constexpr uint32_t TX_TIMEOUT_VALUE = 3000UL
TX timeout in milliseconds.
static constexpr uint32_t ACK_WAIT_MS = 1200UL
HELLO ACK wait duration in milliseconds.
static constexpr uint32_t CMD_WAIT_MS = 1200UL
Optional command wait duration in milliseconds.
static constexpr uint32_t SLEEP_TIME_DEFAULT_MS = 15000UL
Default sleep delay between cycles.
static constexpr uint32_t HELLO_RETRY_GAP_MS = 120UL
Delay between HELLO retries.
static constexpr uint32_t ACK_TURNAROUND_DELAY_MS = 40UL
Delay before sending command ACKs.
static constexpr uint8_t HELLO_MAX_RETRIES = 3
Maximum HELLO attempts per cycle.
static constexpr uint8_t MAX_BUFFER_SIZE = 64
Radio frame buffer size in bytes.
static constexpr uint32_t WATERING_SUPERVISION_TIMEOUT_MS = 90000UL
Safety timeout for watering supervision.
static LoRaSlave * instance = nullptr
Active instance used by static radio callbacks.
Detailed Description
Slave-side LoRa P2P protocol controller.
LoRaSlave owns the radio callbacks, frame buffers, sequence numbers, command handling, battery reporting, watering controller integration, and sleep cadence for one node.
Definition at line 23 of file lora_slave.h.
Member Enumeration Documentation
AckStatus
enum LoRaSlave::AckStatus : uint8_t private
Status values encoded in command acknowledgments.
Enumerator
ACK_STATUS_OK
Command accepted or completed.
ACK_STATUS_ERROR
Command rejected or failed.
Definition at line 84 of file lora_slave.h.
CommandType
enum LoRaSlave::CommandType : uint8_t private
Command codes supported by the slave protocol.
Enumerator
CMD_NONE
No command.
CMD_PING
Connectivity test command.
CMD_LED_ON
Switch the local LED on.
CMD_LED_OFF
Switch the local LED off.
CMD_TEXT_MESSAGE
Text message command acknowledged by the node.
CMD_BATTERY
Battery measurement command.
CMD_REBOOT
MCU reboot command.
CMD_STATUS
General node status query.
CMD_SET_PERIOD
Sleep/HELLO period configuration command.
CMD_VALVE_OPEN
Watering valve open command.
CMD_VALVE_CLOSE
Watering valve close command.
CMD_WATER_TIME
Timed watering start command.
CMD_WATER_ABORT
Timed watering abort command.
CMD_WATER_STATUS
Watering status query command.
CMD_OTA_MODE
BLE OTA mode command.
Definition at line 61 of file lora_slave.h.
FrameType
enum LoRaSlave::FrameType : uint8_t private
Frame types exchanged with the LoRa master.
Enumerator
FRAME_HELLO
Node announcement frame.
FRAME_ACK_HELLO
Master acknowledgment for HELLO.
FRAME_CMD
Command frame sent by the master.
FRAME_ACK_CMD
Command acknowledgment sent by the node.
Definition at line 49 of file lora_slave.h.
Constructor & Destructor Documentation
LoRaSlave()
LoRaSlave::LoRaSlave ()
Constructs a slave controller with default runtime state.
Constructs a LoRaSlave with cleared buffers and default runtime state.
Definition at line 113 of file lora_slave.cpp.
References _justBooted, _lastAckHelloMs, _lastCmdSeq, lastRssi, lastSnr, ledState, rxBuffer, rxDoneFlag, rxErrorFlag, rxSize, rxTimeoutFlag, seqNum, SLEEP_TIME_DEFAULT_MS, sleepTimeMs, txBuffer, txDoneFlag, and txTimeoutFlag.
Member Function Documentation
begin()
void LoRaSlave::begin ()
Initializes LED, watering, and radio resources.
Definition at line 136 of file lora_slave.cpp.
References _lastAckHelloMs, DBG, initRadio(), instance, ledInit(), NODE_ID, readBatteryMilliVolts(), STATUS_LED, watchdogFeed(), and watering.
buildFrame()
uint8_t LoRaSlave::buildFrame (uint8_t type, uint8_t nodeId, uint8_t seq, const uint8_t * payload, uint8_t payloadLen) private
Builds a protocol frame in txBuffer.
Parameters
[in] type Frame type.
[in] nodeId Node identifier.
[in] seq Sequence number.
[in] payload Payload bytes to copy.
[in] payloadLen Payload length in bytes.
Returns
Total frame length written to txBuffer.
Definition at line 368 of file lora_slave.cpp.
References crc16Ccitt(), getFrameTotalLength(), and txBuffer.
Referenced by sendAckCmd(), and sendHelloAndWaitAckOnce().
checkWateringSafety()
void LoRaSlave::checkWateringSafety () private
Runs watering safety supervision.
Definition at line 219 of file lora_slave.cpp.
References _lastAckHelloMs, watering, and WATERING_SUPERVISION_TIMEOUT_MS.
Referenced by loop().
crc16Ccitt()
uint16_t LoRaSlave::crc16Ccitt (const uint8_t * data, uint16_t len) const private
Computes CRC-16/CCITT over a byte buffer.
Parameters
[in] data Pointer to the bytes to checksum.
[in] len Number of bytes to process.
Returns
Computed CRC value.
Definition at line 343 of file lora_slave.cpp.
Referenced by buildFrame(), and validateFrame().
enterBleOtaMode()
void LoRaSlave::enterBleOtaMode () private
Requests BLE OTA mode entry.
Definition at line 1144 of file lora_slave.cpp.
References BleOta::DURATION_DEFAULT_SEC, and BleOta::requestBoot().
Referenced by processOptionalCommand().
getFrameTotalLength()
uint8_t LoRaSlave::getFrameTotalLength (uint8_t payloadLen) const private
Returns total frame length for a payload length.
Parameters
[in] payloadLen Payload length in bytes.
Returns
Total frame length in bytes.
Definition at line 363 of file lora_slave.cpp.
Referenced by buildFrame().
getHelloFlags()
uint8_t LoRaSlave::getHelloFlags () const private
Builds HELLO flag bits.
Returns
HELLO flags byte.
Definition at line 1151 of file lora_slave.cpp.
References _justBooted, and getStatusFlag().
Referenced by sendHelloAndWaitAckOnce().
getStatusFlag()
uint8_t LoRaSlave::getStatusFlag () const private
Builds the current node status flag byte.
Returns
Status flag byte.
Definition at line 274 of file lora_slave.cpp.
Referenced by getHelloFlags(), and processOptionalCommand().
getUptimeSec()
uint32_t LoRaSlave::getUptimeSec () const private
Returns node uptime.
Returns
Uptime in seconds.
Definition at line 276 of file lora_slave.cpp.
Referenced by processOptionalCommand().
initRadio()
bool LoRaSlave::initRadio () private
Initializes the LoRa radio.
Returns
true if radio initialization succeeds, false otherwise.
Definition at line 465 of file lora_slave.cpp.
References DBG, LORA_BANDWIDTH, LORA_CODINGRATE, LORA_FIX_LENGTH_PAYLOAD, LORA_IQ_INVERSION, LORA_PREAMBLE_LENGTH, LORA_SPREADING_FACTOR, LORA_SYMBOL_TIMEOUT, OnCadDone(), OnRxDone(), OnRxError(), OnRxTimeout(), OnTxDone(), OnTxTimeout(), RadioEvents, RF_FREQUENCY, TX_OUTPUT_POWER, and TX_TIMEOUT_VALUE.
Referenced by begin().
ledInit()
void LoRaSlave::ledInit () inline private
Initializes the board LED GPIO.
Definition at line 232 of file lora_slave.cpp.
References ledState, and STATUS_LED.
Referenced by begin().
ledSet()
void LoRaSlave::ledSet (bool on) inline private
Sets the board LED state.
Parameters
[in] on true to turn the LED on, false to turn it off.
Definition at line 242 of file lora_slave.cpp.
References ledState, and STATUS_LED.
Referenced by processOptionalCommand().
loop()
void LoRaSlave::loop ()
Runs one slave protocol cycle.
Definition at line 199 of file lora_slave.cpp.
References checkWateringSafety(), nodeSleep(), processOptionalCommand(), sendHelloAndWaitAck(), sleepTimeMs, watchdogFeed(), and watering.
nextSeq()
uint8_t LoRaSlave::nextSeq () private
Returns and advances the protocol sequence number.
Returns
Sequence number to use for the next outgoing frame.
Definition at line 264 of file lora_slave.cpp.
References seqNum.
Referenced by sendHelloAndWaitAckOnce().
nodeSleep()
void LoRaSlave::nodeSleep (uint32_t sleepMs) private
Waits between protocol cycles.
Parameters
[in] sleepMs Wait duration in milliseconds.
Definition at line 1061 of file lora_slave.cpp.
References watchdogFeed(), and watering.
Referenced by loop().
OnCadDone()
void LoRaSlave::OnCadDone (bool cadResult) static private
Static radio CAD done callback bridge.
Parameters
[in] cadResult CAD result provided by the radio driver.
Definition at line 1139 of file lora_slave.cpp.
Referenced by initRadio().
OnRxDone()
void LoRaSlave::OnRxDone (uint8_t * payload, uint16_t size, int16_t rssi, int8_t snr) static private
Static radio RX done callback bridge.
Parameters
[in] payload Received bytes provided by the radio driver.
[in] size Number of received bytes.
[in] rssi Received RSSI.
[in] snr Received SNR.
Definition at line 1094 of file lora_slave.cpp.
References DBG, and instance.
Referenced by initRadio().
OnRxError()
void LoRaSlave::OnRxError (void) static private
Static radio RX error callback bridge.
Definition at line 1130 of file lora_slave.cpp.
References DBG, and instance.
Referenced by initRadio().
OnRxTimeout()
void LoRaSlave::OnRxTimeout (void) static private
Static radio RX timeout callback bridge.
Definition at line 1122 of file lora_slave.cpp.
References instance.
Referenced by initRadio().
OnTxDone()
void LoRaSlave::OnTxDone (void) static private
Static radio TX done callback bridge.
Definition at line 1076 of file lora_slave.cpp.
References DBG, and instance.
Referenced by initRadio().
OnTxTimeout()
void LoRaSlave::OnTxTimeout (void) static private
Static radio TX timeout callback bridge.
Definition at line 1085 of file lora_slave.cpp.
References DBG, and instance.
Referenced by initRadio().
printFrameDebug()
void LoRaSlave::printFrameDebug (const char * prefix, const uint8_t * buf, uint8_t len) const private
Prints a frame for diagnostics.
Parameters
[in] prefix Text printed before the frame bytes.
[in] buf Buffer containing bytes to print.
[in] len Number of bytes to print.
Definition at line 442 of file lora_slave.cpp.
References DBG.
Referenced by sendFrameAndWaitTx(), and waitForFrame().
processOptionalCommand()
bool LoRaSlave::processOptionalCommand () private
Waits for and processes one optional command from the master.
Returns
true if a command was processed, false otherwise.
Definition at line 800 of file lora_slave.cpp.
References _lastCmdSeq, ACK_STATUS_ERROR, ACK_STATUS_OK, ACK_TURNAROUND_DELAY_MS, CMD_BATTERY, CMD_LED_OFF, CMD_LED_ON, CMD_OTA_MODE, CMD_PING, CMD_REBOOT, CMD_SET_PERIOD, CMD_STATUS, CMD_TEXT_MESSAGE, CMD_VALVE_CLOSE, CMD_VALVE_OPEN, CMD_WAIT_MS, CMD_WATER_ABORT, CMD_WATER_STATUS, CMD_WATER_TIME, DBG, enterBleOtaMode(), fillWaterStatusExtra(), FRAME_CMD, getStatusFlag(), getUptimeSec(), ledSet(), NODE_ID, readBatteryMilliVolts(), rxBuffer, rxSize, sendAckCmd(), sleepTimeMs, validateFrame(), waitForFrame(), watchdogFeed(), and watering.
Referenced by loop().
readBatteryMilliVolts()
uint16_t LoRaSlave::readBatteryMilliVolts () const private
Reads the battery voltage.
Returns
Battery voltage in millivolts.
Definition at line 281 of file lora_slave.cpp.
References REAL_VBAT_MV_PER_LSB, and watchdogFeed().
Referenced by begin(), and processOptionalCommand().
resetFlags()
void LoRaSlave::resetFlags () private
Clears radio event flags and receive size.
Definition at line 254 of file lora_slave.cpp.
References rxDoneFlag, rxErrorFlag, rxSize, rxTimeoutFlag, txDoneFlag, and txTimeoutFlag.
Referenced by sendFrameAndWaitTx(), and waitForFrame().
sendAckCmd()
bool LoRaSlave::sendAckCmd (uint8_t seq, uint8_t cmdCode, uint8_t ackStatus, const uint8_t * extraPayload, uint8_t extraLen) private
Sends a command acknowledgment frame.
Parameters
[in] seq Sequence number to acknowledge.
[in] cmdCode Command code being acknowledged.
[in] ackStatus ACK status byte.
[in] extraPayload Optional extra payload bytes.
[in] extraLen Number of extra payload bytes.
Returns
true if the ACK frame was transmitted, false otherwise.
Definition at line 727 of file lora_slave.cpp.
References buildFrame(), DBG, FRAME_ACK_CMD, NODE_ID, and sendFrameAndWaitTx().
Referenced by processOptionalCommand().
sendFrameAndWaitTx()
bool LoRaSlave::sendFrameAndWaitTx (uint8_t totalLen) private
Sends txBuffer and waits for TX completion.
Parameters
[in] totalLen Number of bytes to send from txBuffer.
Returns
true if transmission completed, false otherwise.
Definition at line 537 of file lora_slave.cpp.
References DBG, printFrameDebug(), resetFlags(), TX_TIMEOUT_VALUE, txBuffer, txDoneFlag, txTimeoutFlag, and watchdogFeed().
Referenced by sendAckCmd(), and sendHelloAndWaitAckOnce().
sendHelloAndWaitAck()
bool LoRaSlave::sendHelloAndWaitAck () private
Sends HELLO frames with retries until ACK or retry exhaustion.
Returns
true if the HELLO is acknowledged, false otherwise.
Definition at line 698 of file lora_slave.cpp.
References DBG, HELLO_MAX_RETRIES, sendHelloAndWaitAckOnce(), and watchdogFeed().
Referenced by loop().
sendHelloAndWaitAckOnce()
bool LoRaSlave::sendHelloAndWaitAckOnce () private
Sends one HELLO frame and waits once for ACK.
Returns
true if the HELLO is acknowledged, false otherwise.
Definition at line 622 of file lora_slave.cpp.
References _justBooted, _lastAckHelloMs, ACK_WAIT_MS, buildFrame(), DBG, FRAME_ACK_HELLO, FRAME_HELLO, getHelloFlags(), nextSeq(), NODE_ID, rxBuffer, rxSize, sendFrameAndWaitTx(), validateFrame(), and waitForFrame().
Referenced by sendHelloAndWaitAck().
validateFrame()
bool LoRaSlave::validateFrame (uint8_t expectedType, uint8_t expectedNode, uint8_t expectedSeq) const private
Validates the last received frame against expected header values.
Parameters
[in] expectedType Expected frame type.
[in] expectedNode Expected node identifier.
[in] expectedSeq Expected sequence number.
Returns
true if the frame is valid and matches the expected values, false otherwise.
Definition at line 388 of file lora_slave.cpp.
References crc16Ccitt(), DBG, MAX_BUFFER_SIZE, rxBuffer, and rxSize.
Referenced by processOptionalCommand(), and sendHelloAndWaitAckOnce().
waitForFrame()
bool LoRaSlave::waitForFrame (uint32_t timeoutMs) private
Waits for one received frame.
Parameters
[in] timeoutMs Receive wait timeout in milliseconds.
Returns
true if a frame was received, false otherwise.
Definition at line 571 of file lora_slave.cpp.
References DBG, MAX_BUFFER_SIZE, printFrameDebug(), resetFlags(), rxBuffer, rxDoneFlag, rxErrorFlag, rxSize, rxTimeoutFlag, and watchdogFeed().
Referenced by processOptionalCommand(), and sendHelloAndWaitAckOnce().
Member Data Documentation
_justBooted
bool LoRaSlave::_justBooted private
true until the first HELLO/status report has been sent.
Definition at line 320 of file lora_slave.h.
Referenced by getHelloFlags(), LoRaSlave(), and sendHelloAndWaitAckOnce().
_lastAckHelloMs
uint32_t LoRaSlave::_lastAckHelloMs private
millis() timestamp of the last acknowledged HELLO.
Definition at line 316 of file lora_slave.h.
Referenced by begin(), checkWateringSafety(), LoRaSlave(), and sendHelloAndWaitAckOnce().
_lastCmdSeq
uint8_t LoRaSlave::_lastCmdSeq private
Last command sequence processed.
Definition at line 317 of file lora_slave.h.
Referenced by LoRaSlave(), and processOptionalCommand().
ACK_TURNAROUND_DELAY_MS
uint32_t LoRaSlave::ACK_TURNAROUND_DELAY_MS = 40UL static constexpr private
Delay before sending command ACKs.
Definition at line 105 of file lora_slave.h.
Referenced by processOptionalCommand().
ACK_WAIT_MS
uint32_t LoRaSlave::ACK_WAIT_MS = 1200UL static constexpr private
HELLO ACK wait duration in milliseconds.
Definition at line 101 of file lora_slave.h.
Referenced by sendHelloAndWaitAckOnce().
CMD_WAIT_MS
uint32_t LoRaSlave::CMD_WAIT_MS = 1200UL static constexpr private
Optional command wait duration in milliseconds.
Definition at line 102 of file lora_slave.h.
Referenced by processOptionalCommand().
HELLO_MAX_RETRIES
uint8_t LoRaSlave::HELLO_MAX_RETRIES = 3 static constexpr private
Maximum HELLO attempts per cycle.
Definition at line 106 of file lora_slave.h.
Referenced by sendHelloAndWaitAck().
HELLO_RETRY_GAP_MS
uint32_t LoRaSlave::HELLO_RETRY_GAP_MS = 120UL static constexpr private
Delay between HELLO retries.
Definition at line 104 of file lora_slave.h.
instance
LoRaSlave * LoRaSlave::instance = nullptr static private
Active instance used by static radio callbacks.
Active LoRaSlave instance used by static radio callback bridges.
Definition at line 114 of file lora_slave.h.
Referenced by begin(), OnRxDone(), OnRxError(), OnRxTimeout(), OnTxDone(), and OnTxTimeout().
lastRssi
volatile int16_t LoRaSlave::lastRssi private
RSSI of the last received frame.
Definition at line 310 of file lora_slave.h.
Referenced by LoRaSlave().
lastSnr
volatile int8_t LoRaSlave::lastSnr private
SNR of the last received frame.
Definition at line 311 of file lora_slave.h.
Referenced by LoRaSlave().
ledState
bool LoRaSlave::ledState private
Cached LED state.
Definition at line 314 of file lora_slave.h.
Referenced by ledInit(), ledSet(), and LoRaSlave().
LORA_BANDWIDTH
uint8_t LoRaSlave::LORA_BANDWIDTH = 0 static constexpr private
SX126x bandwidth code.
Definition at line 92 of file lora_slave.h.
Referenced by initRadio().
LORA_CODINGRATE
uint8_t LoRaSlave::LORA_CODINGRATE = 1 static constexpr private
SX126x coding rate code.
Definition at line 94 of file lora_slave.h.
Referenced by initRadio().
LORA_FIX_LENGTH_PAYLOAD
bool LoRaSlave::LORA_FIX_LENGTH_PAYLOAD = false static constexpr private
false to use variable-length packets.
Definition at line 97 of file lora_slave.h.
Referenced by initRadio().
LORA_IQ_INVERSION
bool LoRaSlave::LORA_IQ_INVERSION = false static constexpr private
false to keep standard IQ polarity.
Definition at line 98 of file lora_slave.h.
Referenced by initRadio().
LORA_PREAMBLE_LENGTH
uint16_t LoRaSlave::LORA_PREAMBLE_LENGTH = 8 static constexpr private
LoRa preamble length, in symbols.
Definition at line 95 of file lora_slave.h.
Referenced by initRadio().
LORA_SPREADING_FACTOR
uint8_t LoRaSlave::LORA_SPREADING_FACTOR = 7 static constexpr private
LoRa spreading factor.
Definition at line 93 of file lora_slave.h.
Referenced by initRadio().
LORA_SYMBOL_TIMEOUT
uint16_t LoRaSlave::LORA_SYMBOL_TIMEOUT = 0 static constexpr private
LoRa symbol timeout for RX configuration.
Definition at line 96 of file lora_slave.h.
Referenced by initRadio().
MAX_BUFFER_SIZE
uint8_t LoRaSlave::MAX_BUFFER_SIZE = 64 static constexpr private
Radio frame buffer size in bytes.
Definition at line 107 of file lora_slave.h.
Referenced by validateFrame(), and waitForFrame().
NODE_ID
uint8_t LoRaSlave::NODE_ID = 3 static constexpr
Static node identifier used in LoRa frames.
Definition at line 29 of file lora_slave.h.
Referenced by begin(), processOptionalCommand(), sendAckCmd(), sendHelloAndWaitAckOnce(), and setup().
RF_FREQUENCY
uint32_t LoRaSlave::RF_FREQUENCY = 865000000UL static constexpr private
LoRa RF frequency, in hertz.
Definition at line 90 of file lora_slave.h.
Referenced by initRadio().
rxBuffer
uint8_t LoRaSlave::rxBuffer[MAX_BUFFER_SIZE] private
Receive frame buffer.
Definition at line 301 of file lora_slave.h.
Referenced by LoRaSlave(), processOptionalCommand(), sendHelloAndWaitAckOnce(), validateFrame(), and waitForFrame().
rxDoneFlag
volatile bool LoRaSlave::rxDoneFlag private
Set when radio RX completes.
Definition at line 305 of file lora_slave.h.
Referenced by LoRaSlave(), resetFlags(), and waitForFrame().
rxErrorFlag
volatile bool LoRaSlave::rxErrorFlag private
Set when radio RX reports an error.
Definition at line 307 of file lora_slave.h.
Referenced by LoRaSlave(), resetFlags(), and waitForFrame().
rxSize
volatile uint16_t LoRaSlave::rxSize private
Size of the last received frame.
Definition at line 309 of file lora_slave.h.
Referenced by LoRaSlave(), processOptionalCommand(), resetFlags(), sendHelloAndWaitAckOnce(), validateFrame(), and waitForFrame().
rxTimeoutFlag
volatile bool LoRaSlave::rxTimeoutFlag private
Set when radio RX times out.
Definition at line 306 of file lora_slave.h.
Referenced by LoRaSlave(), resetFlags(), and waitForFrame().
seqNum
uint8_t LoRaSlave::seqNum private
Protocol sequence counter.
Definition at line 313 of file lora_slave.h.
Referenced by LoRaSlave(), and nextSeq().
SLEEP_TIME_DEFAULT_MS
uint32_t LoRaSlave::SLEEP_TIME_DEFAULT_MS = 15000UL static constexpr private
Default sleep delay between cycles.
Definition at line 103 of file lora_slave.h.
Referenced by LoRaSlave().
sleepTimeMs
uint32_t LoRaSlave::sleepTimeMs private
Current delay between protocol cycles.
Definition at line 315 of file lora_slave.h.
Referenced by loop(), LoRaSlave(), and processOptionalCommand().
TX_OUTPUT_POWER
int8_t LoRaSlave::TX_OUTPUT_POWER = 14 static constexpr private
LoRa transmit power, in dBm.
Definition at line 91 of file lora_slave.h.
Referenced by initRadio().
TX_TIMEOUT_VALUE
uint32_t LoRaSlave::TX_TIMEOUT_VALUE = 3000UL static constexpr private
TX timeout in milliseconds.
Definition at line 100 of file lora_slave.h.
Referenced by initRadio(), and sendFrameAndWaitTx().
txBuffer
uint8_t LoRaSlave::txBuffer[MAX_BUFFER_SIZE] private
Transmit frame buffer.
Definition at line 300 of file lora_slave.h.
Referenced by buildFrame(), LoRaSlave(), and sendFrameAndWaitTx().
txDoneFlag
volatile bool LoRaSlave::txDoneFlag private
Set when radio TX completes.
Definition at line 303 of file lora_slave.h.
Referenced by LoRaSlave(), resetFlags(), and sendFrameAndWaitTx().
txTimeoutFlag
volatile bool LoRaSlave::txTimeoutFlag private
Set when radio TX times out.
Definition at line 304 of file lora_slave.h.
Referenced by LoRaSlave(), resetFlags(), and sendFrameAndWaitTx().
watering
Watering LoRaSlave::watering private
Watering actuator and flow controller.
Definition at line 318 of file lora_slave.h.
Referenced by begin(), checkWateringSafety(), loop(), nodeSleep(), and processOptionalCommand().
WATERING_SUPERVISION_TIMEOUT_MS
uint32_t LoRaSlave::WATERING_SUPERVISION_TIMEOUT_MS = 90000UL static constexpr private
Safety timeout for watering supervision.
Definition at line 109 of file lora_slave.h.
Referenced by checkWateringSafety().
The documentation for this class was generated from the following files:
include/lora_slave.h
src/lora_slave.cpp