My Project: Watering Class Reference
Watering Class Reference
Controls the watering valve and flow metering state.
#include <watering.h>
Public Member Functions
Watering ()
Constructs a Watering controller with default inactive state.
void begin ()
Initializes the watering GPIOs and flow interrupt state.
void loop ()
Runs one watering state update iteration.
bool openValve ()
Opens the watering valve.
bool closeValve ()
Closes the watering valve.
bool startWatering (uint16_t durationSec)
Starts timed watering.
bool abortWatering ()
Aborts the current timed watering operation.
bool isValveOpen () const
Returns the cached valve-open state.
bool isWateringActive () const
Returns whether timed watering is active.
uint16_t getProgrammedDurationSec () const
Returns the programmed watering duration.
uint16_t getRemainingDurationSec () const
Returns the remaining watering duration.
uint32_t getFlowPulses () const
Returns the full flow pulse counter.
uint16_t getFlowPulses16 () const
Returns the flow pulse counter truncated to 16 bits.
uint16_t getLitres16 () const
Returns the water volume value encoded on 16 bits.
uint32_t getPostClosePulses () const
Returns pulses counted during post-close monitoring.
uint8_t isPostCloseLeakDetected () const
Returns the post-close leak detection flag.
void resetFlowCounter ()
Resets flow pulse counters used for watering measurement.
void detachFlowInterrupt ()
Detaches the flow sensor interrupt.
void attachFlowInterrupt ()
Attaches the flow sensor interrupt.
Static Public Member Functions
static void onFlowPulseISR ()
Static interrupt service entry point for flow pulses.
static void pinOutBegin (uint32_t pin)
Configures a pin as an output.
static void pinHigh (uint32_t pin)
Drives a pin high.
static void pinLow (uint32_t pin)
Drives a pin low.
Private Member Functions
void enableBoost9V ()
Enables the 9 V boost supply used for valve actuation.
void disableBoost9V ()
Disables the 9 V boost supply.
void drvIdle ()
Places the valve driver in its idle state.
void drvOpenPulse ()
Sends the driver pulse used to open the valve.
void drvClosePulse ()
Sends the driver pulse used to close the valve.
void updateWateringState ()
Updates timed watering and post-close monitoring state.
Private Attributes
bool valveOpen
true when the valve is considered open.
bool wateringActive
true while timed watering is active.
uint16_t programmedDurationSec
Programmed watering duration in seconds.
uint32_t wateringStartMs
millis() timestamp when timed watering started.
volatile uint32_t flowPulses
Flow pulses counted during watering.
volatile uint32_t postCloseRawPulses
Raw pulses counted after valve close.
volatile uint32_t postClosePulses
Pulses retained for post-close leak detection.
volatile uint32_t postCloseIgnoredPulses
Pulses ignored during the post-close grace period.
bool postCloseMonitorActive
true while post-close monitoring is active.
bool postCloseIgnoreDone
true after the post-close ignore window has elapsed.
bool postCloseLeakDetected
true when post-close pulses exceed the leak threshold.
uint32_t postCloseMonitorStartMs
millis() timestamp when post-close monitoring started.
Static Private Attributes
static Watering * instance = nullptr
Active instance used by the static interrupt callback.
static constexpr uint32_t POST_CLOSE_IGNORE_MS = 5000UL
Initial post-close ignore window, in milliseconds.
static constexpr uint32_t POST_CLOSE_MONITOR_MS = 30000UL
Post-close monitoring duration, in milliseconds.
static constexpr uint32_t POST_CLOSE_LEAK_MIN_PULSES = 5UL
Pulse threshold used to flag a leak.
Detailed Description
Controls the watering valve and flow metering state.
Watering owns the valve state, timed watering state, flow pulse counters, and post-close leak monitoring. It also provides static wrappers for GPIO control and the flow interrupt callback.
Definition at line 21 of file watering.h.
Constructor & Destructor Documentation
Watering()
Watering::Watering ()
Constructs a Watering controller with default inactive state.
Constructs the watering controller with inactive valve and counters reset.
Definition at line 83 of file watering.cpp.
References flowPulses, postCloseIgnoreDone, postCloseIgnoredPulses, postCloseLeakDetected, postCloseMonitorActive, postCloseMonitorStartMs, postClosePulses, postCloseRawPulses, programmedDurationSec, valveOpen, wateringActive, and wateringStartMs.
Member Function Documentation
abortWatering()
bool Watering::abortWatering ()
Aborts the current timed watering operation.
Returns
true if abort handling is accepted, false otherwise.
Definition at line 292 of file watering.cpp.
References closeValve(), programmedDurationSec, valveOpen, wateringActive, and wateringStartMs.
attachFlowInterrupt()
void Watering::attachFlowInterrupt ()
Attaches the flow sensor interrupt.
Definition at line 447 of file watering.cpp.
References onFlowPulseISR(), and WATERING_FLOW_INTERRUPT_MODE.
Referenced by openValve().
begin()
void Watering::begin ()
Initializes the watering GPIOs and flow interrupt state.
Initializes GPIOs, driver idle state, flow input, and counters.
Definition at line 102 of file watering.cpp.
References drvIdle(), flowPulses, instance, pinOutBegin(), postCloseIgnoreDone, postCloseIgnoredPulses, postCloseLeakDetected, postCloseMonitorActive, postCloseMonitorStartMs, postClosePulses, postCloseRawPulses, programmedDurationSec, valveOpen, wateringActive, and wateringStartMs.
closeValve()
bool Watering::closeValve ()
Closes the watering valve.
Returns
true if the close sequence is accepted, false otherwise.
Definition at line 232 of file watering.cpp.
References DBG, disableBoost9V(), drvClosePulse(), enableBoost9V(), postCloseIgnoreDone, postCloseIgnoredPulses, postCloseLeakDetected, postCloseMonitorActive, postCloseMonitorStartMs, postClosePulses, postCloseRawPulses, programmedDurationSec, valveOpen, WATERING_BOOST_SIMULATION_MS, wateringActive, and wateringStartMs.
Referenced by abortWatering(), and updateWateringState().
detachFlowInterrupt()
void Watering::detachFlowInterrupt ()
Detaches the flow sensor interrupt.
Definition at line 464 of file watering.cpp.
Referenced by loop().
disableBoost9V()
void Watering::disableBoost9V () private
Disables the 9 V boost supply.
Definition at line 409 of file watering.cpp.
References pinLow().
Referenced by closeValve(), and openValve().
drvClosePulse()
void Watering::drvClosePulse () private
Sends the driver pulse used to close the valve.
Definition at line 434 of file watering.cpp.
References drvIdle(), pinHigh(), pinLow(), WATERING_POST_PULSE_MS, and WATERING_PULSE_MS.
Referenced by closeValve().
drvIdle()
void Watering::drvIdle () private
Places the valve driver in its idle state.
Definition at line 414 of file watering.cpp.
References pinLow().
Referenced by begin(), drvClosePulse(), and drvOpenPulse().
drvOpenPulse()
void Watering::drvOpenPulse () private
Sends the driver pulse used to open the valve.
Definition at line 421 of file watering.cpp.
References drvIdle(), pinHigh(), pinLow(), WATERING_POST_PULSE_MS, and WATERING_PULSE_MS.
Referenced by openValve().
enableBoost9V()
void Watering::enableBoost9V () private
Enables the 9 V boost supply used for valve actuation.
Definition at line 403 of file watering.cpp.
References pinHigh(), and WATERING_BOOST_STABILIZE_MS.
Referenced by closeValve(), and openValve().
getFlowPulses()
uint32_t Watering::getFlowPulses () const
Returns the full flow pulse counter.
Returns
Flow pulse count.
Definition at line 340 of file watering.cpp.
References flowPulses.
Referenced by fillWaterStatusExtra(), getFlowPulses16(), and getLitres16().
getFlowPulses16()
uint16_t Watering::getFlowPulses16 () const
Returns the flow pulse counter truncated to 16 bits.
Returns
Flow pulse count as uint16_t.
Definition at line 348 of file watering.cpp.
References getFlowPulses().
getLitres16()
uint16_t Watering::getLitres16 () const
Returns the water volume value encoded on 16 bits.
Returns
Water volume value as uint16_t.
Definition at line 358 of file watering.cpp.
References FLOW_PULSES_PER_LITRE, and getFlowPulses().
Referenced by fillWaterStatusExtra().
getPostClosePulses()
uint32_t Watering::getPostClosePulses () const
Returns pulses counted during post-close monitoring.
Returns
Post-close pulse count.
Definition at line 368 of file watering.cpp.
References postClosePulses.
Referenced by fillWaterStatusExtra().
getProgrammedDurationSec()
uint16_t Watering::getProgrammedDurationSec () const
Returns the programmed watering duration.
Returns
Duration in seconds.
Definition at line 319 of file watering.cpp.
References programmedDurationSec.
Referenced by fillWaterStatusExtra().
getRemainingDurationSec()
uint16_t Watering::getRemainingDurationSec () const
Returns the remaining watering duration.
Returns
Remaining duration in seconds.
Definition at line 324 of file watering.cpp.
References programmedDurationSec, wateringActive, and wateringStartMs.
Referenced by fillWaterStatusExtra().
isPostCloseLeakDetected()
uint8_t Watering::isPostCloseLeakDetected () const
Returns the post-close leak detection flag.
Returns
1 when a leak is detected, 0 otherwise.
Definition at line 376 of file watering.cpp.
References postCloseLeakDetected.
Referenced by fillWaterStatusExtra().
isValveOpen()
bool Watering::isValveOpen () const
Returns the cached valve-open state.
Returns
true if the valve is considered open, false otherwise.
Definition at line 309 of file watering.cpp.
References valveOpen.
Referenced by fillWaterStatusExtra().
isWateringActive()
bool Watering::isWateringActive () const
Returns whether timed watering is active.
Returns
true if watering is active, false otherwise.
Definition at line 314 of file watering.cpp.
References wateringActive.
Referenced by fillWaterStatusExtra().
loop()
void Watering::loop ()
Runs one watering state update iteration.
Updates timed watering and post-close leak monitoring.
Definition at line 143 of file watering.cpp.
References DBG, detachFlowInterrupt(), POST_CLOSE_IGNORE_MS, POST_CLOSE_LEAK_MIN_PULSES, POST_CLOSE_MONITOR_MS, postCloseIgnoreDone, postCloseIgnoredPulses, postCloseLeakDetected, postCloseMonitorActive, postCloseMonitorStartMs, postClosePulses, postCloseRawPulses, and updateWateringState().
onFlowPulseISR()
void Watering::onFlowPulseISR () static
Static interrupt service entry point for flow pulses.
Definition at line 388 of file watering.cpp.
References instance.
Referenced by attachFlowInterrupt().
openValve()
bool Watering::openValve ()
Opens the watering valve.
Returns
true if the open sequence is accepted, false otherwise.
Definition at line 207 of file watering.cpp.
References attachFlowInterrupt(), disableBoost9V(), drvOpenPulse(), enableBoost9V(), postCloseIgnoreDone, postCloseMonitorActive, valveOpen, and WATERING_BOOST_SIMULATION_MS.
Referenced by startWatering().
pinHigh()
void Watering::pinHigh (uint32_t pin) static
Drives a pin high.
Parameters
[in] pin Pin identifier.
Definition at line 501 of file watering.cpp.
Referenced by drvClosePulse(), drvOpenPulse(), and enableBoost9V().
pinLow()
void Watering::pinLow (uint32_t pin) static
Drives a pin low.
Parameters
[in] pin Pin identifier.
Definition at line 506 of file watering.cpp.
Referenced by disableBoost9V(), drvClosePulse(), drvIdle(), and drvOpenPulse().
pinOutBegin()
void Watering::pinOutBegin (uint32_t pin) static
Configures a pin as an output.
Parameters
[in] pin Pin identifier.
Definition at line 495 of file watering.cpp.
Referenced by begin().
resetFlowCounter()
void Watering::resetFlowCounter ()
Resets flow pulse counters used for watering measurement.
Definition at line 381 of file watering.cpp.
References flowPulses.
Referenced by startWatering().
startWatering()
bool Watering::startWatering (uint16_t durationSec)
Starts timed watering.
Parameters
[in] durationSec Requested watering duration in seconds.
Returns
true if timed watering starts, false otherwise.
Definition at line 268 of file watering.cpp.
References openValve(), programmedDurationSec, resetFlowCounter(), valveOpen, wateringActive, and wateringStartMs.
updateWateringState()
void Watering::updateWateringState () private
Updates timed watering and post-close monitoring state.
Definition at line 479 of file watering.cpp.
References closeValve(), programmedDurationSec, wateringActive, and wateringStartMs.
Referenced by loop().
Member Data Documentation
flowPulses
volatile uint32_t Watering::flowPulses private
Flow pulses counted during watering.
Definition at line 169 of file watering.h.
Referenced by begin(), getFlowPulses(), resetFlowCounter(), and Watering().
instance
Watering * Watering::instance = nullptr static private
Active instance used by the static interrupt callback.
Active Watering instance used by the static flow interrupt callback.
Definition at line 163 of file watering.h.
Referenced by begin(), and onFlowPulseISR().
POST_CLOSE_IGNORE_MS
uint32_t Watering::POST_CLOSE_IGNORE_MS = 5000UL static constexpr private
Initial post-close ignore window, in milliseconds.
Definition at line 178 of file watering.h.
Referenced by loop().
POST_CLOSE_LEAK_MIN_PULSES
uint32_t Watering::POST_CLOSE_LEAK_MIN_PULSES = 5UL static constexpr private
Pulse threshold used to flag a leak.
Definition at line 180 of file watering.h.
Referenced by loop().
POST_CLOSE_MONITOR_MS
uint32_t Watering::POST_CLOSE_MONITOR_MS = 30000UL static constexpr private
Post-close monitoring duration, in milliseconds.
Definition at line 179 of file watering.h.
Referenced by loop().
postCloseIgnoreDone
bool Watering::postCloseIgnoreDone private
true after the post-close ignore window has elapsed.
Definition at line 175 of file watering.h.
Referenced by begin(), closeValve(), loop(), openValve(), and Watering().
postCloseIgnoredPulses
volatile uint32_t Watering::postCloseIgnoredPulses private
Pulses ignored during the post-close grace period.
Definition at line 173 of file watering.h.
Referenced by begin(), closeValve(), loop(), and Watering().
postCloseLeakDetected
bool Watering::postCloseLeakDetected private
true when post-close pulses exceed the leak threshold.
Definition at line 176 of file watering.h.
Referenced by begin(), closeValve(), isPostCloseLeakDetected(), loop(), and Watering().
postCloseMonitorActive
bool Watering::postCloseMonitorActive private
true while post-close monitoring is active.
Definition at line 174 of file watering.h.
Referenced by begin(), closeValve(), loop(), openValve(), and Watering().
postCloseMonitorStartMs
uint32_t Watering::postCloseMonitorStartMs private
millis() timestamp when post-close monitoring started.
Definition at line 177 of file watering.h.
Referenced by begin(), closeValve(), loop(), and Watering().
postClosePulses
volatile uint32_t Watering::postClosePulses private
Pulses retained for post-close leak detection.
Definition at line 172 of file watering.h.
Referenced by begin(), closeValve(), getPostClosePulses(), loop(), and Watering().
postCloseRawPulses
volatile uint32_t Watering::postCloseRawPulses private
Raw pulses counted after valve close.
Definition at line 171 of file watering.h.
Referenced by begin(), closeValve(), loop(), and Watering().
programmedDurationSec
uint16_t Watering::programmedDurationSec private
Programmed watering duration in seconds.
Definition at line 167 of file watering.h.
Referenced by abortWatering(), begin(), closeValve(), getProgrammedDurationSec(), getRemainingDurationSec(), startWatering(), updateWateringState(), and Watering().
valveOpen
bool Watering::valveOpen private
true when the valve is considered open.
Definition at line 165 of file watering.h.
Referenced by abortWatering(), begin(), closeValve(), isValveOpen(), openValve(), startWatering(), and Watering().
wateringActive
bool Watering::wateringActive private
true while timed watering is active.
Definition at line 166 of file watering.h.
Referenced by abortWatering(), begin(), closeValve(), getRemainingDurationSec(), isWateringActive(), startWatering(), updateWateringState(), and Watering().
wateringStartMs
uint32_t Watering::wateringStartMs private
millis() timestamp when timed watering started.
Definition at line 168 of file watering.h.
Referenced by abortWatering(), begin(), closeValve(), getRemainingDurationSec(), startWatering(), updateWateringState(), and Watering().
The documentation for this class was generated from the following files:
include/watering.h
src/watering.cpp