My Project: src/main.cpp File Reference
main.cpp File Reference
Arduino entry point for the LoRa watering slave node.
#include <Arduino.h>
#include "ble_ota.h"
#include "lora_slave.h"
#include "watchdog_simple.h"
Macros
#define DBG Serial
Debug serial stream.
#define DBG_BAUD 115200
Debug serial baud rate.
#define DBG_WAIT_MS 4000
Maximum wait time for USB serial connection, in milliseconds.
Functions
void setup ()
Arduino setup entry point.
void loop ()
Arduino main loop entry point.
Variables
static constexpr uint32_t WATCHDOG_TIMEOUT_MS = 30000UL
Watchdog timeout used by the application, in milliseconds.
LoRaSlave loraSlave
Global LoRa slave protocol controller.
Detailed Description
Arduino entry point for the LoRa watering slave node.
This file initializes early watering power pins, optional BLE OTA boot mode, watchdog supervision, and the LoRaSlave protocol controller.
Definition in file main.cpp.
Macro Definition Documentation
DBG
#define DBG Serial
Debug serial stream.
Definition at line 16 of file main.cpp.
DBG_BAUD
#define DBG_BAUD 115200
Debug serial baud rate.
Definition at line 20 of file main.cpp.
Referenced by setup().
DBG_WAIT_MS
#define DBG_WAIT_MS 4000
Maximum wait time for USB serial connection, in milliseconds.
Definition at line 24 of file main.cpp.
Referenced by setup().
Function Documentation
loop()
void loop ()
Arduino main loop entry point.
Services BLE OTA mode when active; otherwise delegates the cycle to LoRaSlave.
Definition at line 85 of file main.cpp.
References BleOta::isActive(), BleOta::loop(), loraSlave, and watchdogFeed().
setup()
void setup ()
Arduino setup entry point.
Performs early GPIO shutdown for watering power paths, starts the debug serial interface, checks for BLE OTA boot request, starts the watchdog, and initializes the LoRa slave controller.
Definition at line 43 of file main.cpp.
References BleOta::begin(), BleOta::clearBootRequest(), DBG, DBG_BAUD, DBG_WAIT_MS, BleOta::isRequestedAtBoot(), loraSlave, LoRaSlave::NODE_ID, WATCHDOG_TIMEOUT_MS, watchdogBegin(), and watchdogFeed().
Variable Documentation
loraSlave
LoRaSlave loraSlave
Global LoRa slave protocol controller.
Definition at line 34 of file main.cpp.
Referenced by loop(), and setup().
WATCHDOG_TIMEOUT_MS
uint32_t WATCHDOG_TIMEOUT_MS = 30000UL static constexpr
Watchdog timeout used by the application, in milliseconds.
Definition at line 29 of file main.cpp.
Referenced by setup().