My Project: BleOta Namespace Reference
BleOta Namespace Reference
Functions and constants for firmware update over BLE.
Functions
static void connect_callback (uint16_t conn_handle)
Bluefruit connection callback.
static void disconnect_callback (uint16_t conn_handle, uint8_t reason)
Bluefruit disconnection callback.
uint32_t sanitizeDurationSec (uint32_t durationSec)
Clamps a requested OTA duration to the supported range.
void requestBoot (uint32_t durationSec)
Stores the OTA boot marker in GPREGRET.
bool isRequestedAtBoot ()
Checks whether GPREGRET contains the OTA boot marker.
void clearBootRequest ()
Clears the OTA boot marker from GPREGRET.
void begin (const char *deviceName)
Starts BLE DFU advertising under the provided device name.
void loop ()
Services OTA timeout handling.
bool isActive ()
Returns whether OTA mode is currently active.
Variables
const uint8_t OTA_BOOT_MAGIC = 0xA5
Magic value stored in GPREGRET to request OTA mode after reset.
static BLEDfu bledfu
Bluefruit DFU service object.
static bool g_active = false
true while BLE OTA mode is active.
static uint32_t g_startedMs = 0
millis() timestamp when OTA mode started.
static const uint32_t OTA_ADVERTISING_WINDOW_MS = DURATION_DEFAULT_SEC * 1000UL
Fixed BLE advertising window used by this implementation, in milliseconds.
static constexpr uint32_t DURATION_MIN_SEC = 60UL
Minimum allowed OTA window duration, in seconds.
static constexpr uint32_t DURATION_MAX_SEC = 1800UL
Maximum allowed OTA window duration, in seconds.
static constexpr uint32_t DURATION_DEFAULT_SEC = 300UL
Default OTA duration used for invalid or unspecified requests.
Detailed Description
Functions and constants for firmware update over BLE.
Function Documentation
begin()
void BleOta::begin (const char * deviceName)
Starts BLE DFU advertising under the provided device name.
Initializes the BLE OTA service.
Postcondition
g_active is true and g_startedMs contains the start timestamp.
Parameters
[in] deviceName BLE name advertised by the device.
Precondition
deviceName must point to a valid C string.
Definition at line 110 of file ble_ota.cpp.
References bledfu, connect_callback(), disconnect_callback(), g_active, and g_startedMs.
Referenced by setup().
clearBootRequest()
void BleOta::clearBootRequest ()
Clears the OTA boot marker from GPREGRET.
Clears the OTA boot request persisted by requestBoot().
Definition at line 100 of file ble_ota.cpp.
Referenced by setup().
connect_callback()
void BleOta::connect_callback (uint16_t conn_handle) static
Bluefruit connection callback.
Parameters
[in] conn_handle Connection handle provided by the BLE stack.
Definition at line 43 of file ble_ota.cpp.
Referenced by begin().
disconnect_callback()
void BleOta::disconnect_callback (uint16_t conn_handle, uint8_t reason) static
Bluefruit disconnection callback.
Parameters
[in] conn_handle Connection handle provided by the BLE stack.
[in] reason BLE disconnection reason.
Definition at line 55 of file ble_ota.cpp.
Referenced by begin().
isActive()
bool BleOta::isActive ()
Returns whether OTA mode is currently active.
Indicates whether BLE OTA mode is active.
Returns
true if BLE OTA mode is active, false otherwise.
Definition at line 168 of file ble_ota.cpp.
References g_active.
Referenced by loop().
isRequestedAtBoot()
bool BleOta::isRequestedAtBoot ()
Checks whether GPREGRET contains the OTA boot marker.
Indicates whether a BLE OTA boot was requested.
Returns
true if OTA mode was requested for this boot, false otherwise.
true if an OTA request is present at startup, false otherwise.
Definition at line 92 of file ble_ota.cpp.
References OTA_BOOT_MAGIC.
Referenced by setup().
loop()
void BleOta::loop ()
Services OTA timeout handling.
Runs one service iteration of the BLE OTA mode.
Definition at line 148 of file ble_ota.cpp.
References g_active, g_startedMs, and OTA_ADVERTISING_WINDOW_MS.
Referenced by loop().
requestBoot()
void BleOta::requestBoot (uint32_t durationSec)
Stores the OTA boot marker in GPREGRET.
Requests a later restart into BLE OTA mode.
Note
The current implementation does not persist durationSec across reset.
Parameters
[in] durationSec Requested OTA window duration, in seconds.
Postcondition
An OTA boot request is made visible to isRequestedAtBoot().
Definition at line 81 of file ble_ota.cpp.
References OTA_BOOT_MAGIC.
Referenced by LoRaSlave::enterBleOtaMode().
sanitizeDurationSec()
uint32_t BleOta::sanitizeDurationSec (uint32_t durationSec)
Clamps a requested OTA duration to the supported range.
Clamps an OTA duration to the accepted interval.
Returns
durationSec when valid, otherwise DURATION_DEFAULT_SEC.
Parameters
[in] durationSec Requested duration, in seconds.
Returns
Corrected duration in the [DURATION_MIN_SEC, DURATION_MAX_SEC] range.
Definition at line 67 of file ble_ota.cpp.
References DURATION_DEFAULT_SEC, and DURATION_MAX_SEC.
Variable Documentation
bledfu
BLEDfu BleOta::bledfu static
Bluefruit DFU service object.
Definition at line 21 of file ble_ota.cpp.
Referenced by begin().
DURATION_DEFAULT_SEC
uint32_t BleOta::DURATION_DEFAULT_SEC = 300UL static constexpr
Default OTA duration used for invalid or unspecified requests.
Definition at line 35 of file ble_ota.h.
Referenced by LoRaSlave::enterBleOtaMode(), and sanitizeDurationSec().
DURATION_MAX_SEC
uint32_t BleOta::DURATION_MAX_SEC = 1800UL static constexpr
Maximum allowed OTA window duration, in seconds.
Definition at line 31 of file ble_ota.h.
Referenced by sanitizeDurationSec().
DURATION_MIN_SEC
uint32_t BleOta::DURATION_MIN_SEC = 60UL static constexpr
Minimum allowed OTA window duration, in seconds.
Definition at line 27 of file ble_ota.h.
g_active
bool BleOta::g_active = false static
true while BLE OTA mode is active.
Definition at line 25 of file ble_ota.cpp.
Referenced by begin(), isActive(), and loop().
g_startedMs
uint32_t BleOta::g_startedMs = 0 static
millis() timestamp when OTA mode started.
Definition at line 29 of file ble_ota.cpp.
Referenced by begin(), and loop().
OTA_ADVERTISING_WINDOW_MS
const uint32_t BleOta::OTA_ADVERTISING_WINDOW_MS = DURATION_DEFAULT_SEC * 1000UL static
Fixed BLE advertising window used by this implementation, in milliseconds.
Definition at line 36 of file ble_ota.cpp.
Referenced by loop().
OTA_BOOT_MAGIC
const uint8_t BleOta::OTA_BOOT_MAGIC = 0xA5
Magic value stored in GPREGRET to request OTA mode after reset.
OTA boot request marker stored by the implementation.
Definition at line 16 of file ble_ota.cpp.
Referenced by isRequestedAtBoot(), and requestBoot().