My Project: include/watchdog_simple.h File Reference
watchdog_simple.h File Reference
Minimal interface for driving the nRF52 hardware watchdog.
#include <Arduino.h>
Functions
void watchdogBegin (uint32_t timeoutMs=20000)
Initializes and starts the hardware watchdog.
void watchdogFeed ()
Feeds the watchdog if it has been started.
bool watchdogIsRunning ()
Indicates whether the watchdog was started through this interface.
Detailed Description
Minimal interface for driving the nRF52 hardware watchdog.
Definition in file watchdog_simple.h.
Function Documentation
watchdogBegin()
void watchdogBegin (uint32_t timeoutMs)
Initializes and starts the hardware watchdog.
Initializes and starts the nRF watchdog peripheral.
Parameters
[in] timeoutMs Maximum time without a feed before reset, in milliseconds.
Postcondition
watchdogIsRunning() returns true if initialization was performed.
Warning
Once the nRF watchdog is started, it generally cannot be stopped before a hardware reset.
Initializes and starts the hardware watchdog.
Warning
The hardware watchdog cannot be stopped after it is started.
Definition at line 23 of file watchdog_simple.cpp.
References watchdogIsRunning().
Referenced by setup().
watchdogFeed()
void watchdogFeed ()
Feeds the watchdog if it has been started.
Reloads watchdog channel RR0 when the watchdog is active.
Feeds the watchdog if it has been started.
Definition at line 54 of file watchdog_simple.cpp.
References watchdogIsRunning().
Referenced by LoRaSlave::begin(), loop(), LoRaSlave::loop(), LoRaSlave::nodeSleep(), LoRaSlave::processOptionalCommand(), LoRaSlave::readBatteryMilliVolts(), LoRaSlave::sendFrameAndWaitTx(), LoRaSlave::sendHelloAndWaitAck(), setup(), and LoRaSlave::waitForFrame().
watchdogIsRunning()
bool watchdogIsRunning ()
Indicates whether the watchdog was started through this interface.
Returns the hardware watchdog run status.
Returns
true if watchdogBegin() has already started the watchdog, false otherwise.
Indicates whether the watchdog was started through this interface.
Returns
true if the NRF_WDT peripheral is running, false otherwise.
Definition at line 13 of file watchdog_simple.cpp.
Referenced by watchdogBegin(), and watchdogFeed().